# Generated by Django 5.1.2 on 2024-10-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0004_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
